version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${APP_PORT:-3000}:${CONTAINER_PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${CONTAINER_PORT:-3000}
      - HOST=0.0.0.0
    volumes:
      # Persist uploads and data
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "http.get('http://localhost:3000/api/ping', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
    profiles:
      - dev
